curl -o sounds\ghost_sayori_kill.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_kill.ogg
curl -o sounds\ghost_sayori_kill_success.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_kill_success.ogg
curl -o sounds\ghost_sayori_pain1.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_pain1.ogg
curl -o sounds\ghost_sayori_pain2.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_pain2.ogg
curl -o sounds\ghost_sayori_resist1.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_resist1.ogg
curl -o sounds\ghost_sayori_resist2.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_resist2.ogg
curl -o sounds\ghost_sayori_resist3.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_resist3.ogg
curl -o sounds\ghost_sayori_shoot.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_shoot.ogg
curl -o sounds\ghost_sayori_teleport.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_teleport.ogg
curl -o sounds\ghost_sayori_teleportspawn.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_teleportspawn.ogg
curl -o sounds\ghost_sayori_voice.ogg https://raw.githubusercontent.com/montage8/updater-sp/master/ghost_sayori_voice.ogg
curl -o sounds\ivan_fire.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_fire.ogg
curl -o sounds\ivan_build.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_build.ogg
curl -o sounds\ivan_heal.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_heal.ogg
curl -o sounds\ivan_kill.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_kill.ogg
curl -o sounds\ivan_loop1.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_loop1.ogg
curl -o sounds\ivan_pain1.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_pain1.ogg
curl -o sounds\ivan_rocket_warn.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_rocket_warn.ogg
curl -o sounds\ivan_shoot.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_shoot.ogg
curl -o sounds\ivan_shootdist.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_shootdist.ogg
curl -o sounds\ivan_teleport.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_teleport.ogg
curl -o sounds\ivan_voice.ogg https://raw.githubusercontent.com/montage8/sp-sound-ivan/master/ivan_voice.ogg